# Generated by Django 6.0.1 on 2026-01-29 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMSapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentdata',
            table='StudentData',
        ),
    ]
