# Generated by Django 6.0.1 on 2026-01-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSapp', '0002_alter_studentdata_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
