# Generated by Django 6.0.1 on 2026-01-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSapp', '0003_studentdata_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='review',
            field=models.TextField(blank=True, default='No data provided', help_text='Give Your Feedback'),
        ),
    ]
