# Generated by Django 6.0.1 on 2026-01-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSapp', '0004_studentdata_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
